### ISSUE TITLE
Uncaught exception for invalid command line arguments

### ISSUE THREAD

**Issue by awvwgk** [Isurwars/Correlation#1]
Running this project with invalid command line arguments like a string passed to the ``-a`` option results in an unhandled exception:

    Starting program: /home/awvwgk/projects/src/joss/Correlation/_build_debug/Correlation test/test_1/xSi.car -a str
    terminate called after throwing an instance of 'std::invalid_argument'
      what():  stof

    Program received signal SIGABRT, Aborted.
    0x00007ffff7ac5615 in raise () from /usr/lib/libc.so.6

Preferrably the exception is caught by the program and converted to a meaningful error message for the user to understand the problem with the input.

**Comment by Isurwars** [comment]
Initial error catching in argument parsing has been added in the testing branch: https://github.com/Isurwars/Correlation/tree/Testing

**Comment by awvwgk** [comment]
Thanks, this seems to resolve some of the issues with the command line interface. I encountered a strange issue with the `-w` option (see #3).
