### ISSUE TITLE
Output file documentation

### ISSUE THREAD

**Issue by CFGrote** [Isurwars/Correlation#12]
To ensure interpretability, please add units to all columns and describe the columns in the readme.

**Comment by CFGrote** [comment]
PAD file: unit of angle (radian, degree, ...?)

**Comment by CFGrote** [comment]
g.csv, G_.csv: What is the unit of r (A, nm, ... ?)

**Comment by Isurwars** [comment]
Added in RC5.

**Comment by Isurwars** [comment]
Added units in RC7, currently all units are reported in the header.
