### ISSUE TITLE
25000 atoms

### ISSUE THREAD

**Issue by CFGrote** [Isurwars/Correlation#13]
In paper.md (branch Testing) you still mention 25000 atoms as the limit of what your code can handle but state in https://github.com/openjournals/joss-reviews/issues/2976#issuecomment-874199005 that it can now handle up to 100000 atoms.

**Comment by Isurwars** [comment]
Corrected in RC5.

We include a 20,000+ atoms sample for testing, The ram limitation in my home (32GB) doesn't let me test with a larger sample. 

Hope the next week we can finally return to the university to test the code with a larger sample in the university workstation with 128GB of RAM.

**Comment by Isurwars** [comment]
The paper.md has been corrected since RC5, will add a test file of 140,000+ atoms provided by Alejandro de Leon and Salvador Villarreal as private communication in RC9.

This test required at least an hour to complete, and more than 16GB of RAM were used in the process.
