### ISSUE TITLE
 List of improvements into paper.md

### ISSUE THREAD

**Issue by CFGrote** [Isurwars/Correlation#16]
This is only a minor comment: You make excellent suggestions on how to improve your code (in your response to my earlier comments). Why not include them in the paper.md? Even better, make gh issues for each one so they will not be forgotten ;).

**Comment by Isurwars** [comment]
Added in RC5.

**Comment by Isurwars** [comment]
I have merge the testing branch to main incorporating the requested changes to paper.md.

**Comment by Isurwars** [comment]
Added the future features as issues.
