### ISSUE TITLE
Problems when installing on centos8

### ISSUE THREAD

**Issue by yunai2384** [Isurwars/Correlation#36]
I have gcc automake autoconf and  libtool installed, and make sure the permission is done according to "chmod +x *". The problem comes when I type "./configure":

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `

Sorry to bother you, but I’d appreciate some help.

**Comment by Isurwars** [comment]
Hi @yunai2384.

Can you help me trying to run:
`dos2unix configure.ac`

and then run again on the root folder
`./configure`

This seems to be a conflict with the windows carriage return.

**Comment by yunai2384** [comment]
sorry, the error still exists with the same output.

(base) [yunai@yunai Correlation]$  dos2unix configure.ac
dos2unix: converting file configure.ac to Unix format...
(base) [yunai@yunai Correlation]$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C++... yes
checking whether g++ accepts -g... yes
checking for g++ option to enable C++11 features... none needed
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
.in'ig.status: error: cannot find input file: `

**Comment by Isurwars** [comment]
Will investigate further in a workstation with centOS, thanks for the report @yunai2384

**Comment by Isurwars** [comment]
There seems to be an incompatibility with autoconf in CentOS, please try to run:

`autoreconf`

and then try to run:

`./configure`

These seems to fix the problem on my workstation in CentOS 7

**Comment by yunai2384** [comment]
Here is the output:

(base) [yunai@yunai Correlation]$ autoconf 
configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
(base) [yunai@yunai Correlation]$ autoconf 
(base) [yunai@yunai Correlation]$ autoconf 
(base) [yunai@yunai Correlation]$ ./configure
./configure: line 1733: syntax error near unexpected token `-Wall'
./configure: line 1733: `AM_INIT_AUTOMAKE(-Wall -Werror foreign)'

Thanks!

**Comment by Isurwars** [comment]
> 
> 
> Here is the output:
> 
> (base) [yunai@yunai Correlation]$ autoconf
> configure.ac:5: error: possibly undefined macro: AM_INIT_AUTOMAKE
> If this token and others are legitimate, please use m4_pattern_allow.
> See the Autoconf documentation.
> (base) [yunai@yunai Correlation]$ autoconf
> (base) [yunai@yunai Correlation]$ autoconf
> (base) [yunai@yunai Correlation]$ ./configure
> ./configure: line 1733: syntax error near unexpected token `-Wall' ./configure: line 1733: `AM_INIT_AUTOMAKE(-Wall -Werror foreign)'
> 
> Thanks!

I  get a similar output with `autoconf`
There are to options, delete the configure before running 
`autoconf`
`automake`
or the easier option: `autoreconf` to update the `configure` and  overwrite the `configure` included in the release.

**Comment by yunai2384** [comment]
The problem has been solved, thank you very much!
